### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by vigji** [3d-pli/fastpli#2]
Just skimming through the project I could find several places in which the usage of linting tools such as `flake8` and `black` would help, eg:
- inconsistent single and double quote  usage;
- unused import statements
- unused, commented out code (this should not live in master)

Ideally those can be running together with the CI mentioned in #1 for testing linting together with test passing.

**Comment by fmatuschke** [comment]
Thanks for the suggestions. I added an automatic linting process to my workflow and cleaned everything up. As you suggest they are also implemented inside the CI. To configure the style I added an `.style.yapf` and `.flake8` file to the repository.
