### ISSUE TITLE
Add dependencies versions

### ISSUE THREAD

**Issue by vigji** [3d-pli/fastpli#3]
I am trying to get the testing running on the WSL. I run into 2 problems so far
- The dependencies do not specify minimum version requirements. Some tests were failing for me as `np.cross` requires `numpy>=1.19`
- Running the tests a second times was failing at a very preliminary stage as a temporary file `/tmp/simply_rep.h5` could not be written as it was already present. Maybe there should be a more gracious handling of temporary file removal if tests fail

**Comment by fmatuschke** [comment]
I added the current dependencies to the `setup.py` file. I hope this fixes the Issue.
Additionally, I changed the testing process. Every temporary file is now created inside the test path and cleaned up automatically.
When an error occurs which interrupts the cleanup process, the files will be now overwritten.

FYI, I also added a sentence where additional information about the WSL can be found.
