### ISSUE TITLE
warning during install

### ISSUE THREAD

**Issue by glyg** [3d-pli/fastpli#8]
Although install proceeded without problems, I had the following warning:
```
WARNING: Built wheel for fastpli is invalid: Metadata 1.2 mandates PEP 440 version, but 'v1.1.0a6.dev1-g2b24015-Release' is not
Failed to build fastpli
Installing collected packages: numpy, llvmlite, scipy, numba, h5py, fastpli
    Running setup.py install for fastpli ... done
  DEPRECATION: fastpli was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
```

I assume it is a simple fix to not put the git hash in  the version, but I'm not familiar with the system you're using 

This is a very minor problem, please feel free to  not fix :)

**Comment by fmatuschke** [comment]
That's correct. For the purpose of traceability I automatically generate the version number from the last tag version name. However, if a new commit has been used without a version tag, the additional number of commits after the last tag is added (here 1) and the git hash will be added additionally. If someone decides to use a commit, e.g. in another development branch, this warning also reminds them. However, I should make it more obvious than the this.

Clearly in the future I will only push/pull request new releases of the code. For the purpose of the current review process I will push also little changes, so all reviewers can see the changes. Therefore, you can ignore this warning at this point.

**Comment by glyg** [comment]
Thanks, sounds legit :)
